"""multi-grade: grades + unit.grade_id

Revision ID: f83b8b7030ef
Revises: b24031ebef9b
Create Date: 2026-06-08 16:08:25.865247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83b8b7030ef'
down_revision: Union[str, Sequence[str], None] = 'b24031ebef9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_units_grade_id'), ['grade_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_units_grade_id_grades', 'grades', ['grade_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('fk_units_grade_id_grades', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_units_grade_id'))
        batch_op.drop_column('grade_id')

    op.drop_table('grades')
    # ### end Alembic commands ###
