"""add answer_text to answer_log

Revision ID: 983be800febc
Revises: 9602e47b6e71
Create Date: 2026-06-05 19:17:08.929403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983be800febc'
down_revision: Union[str, Sequence[str], None] = '9602e47b6e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_text', sa.String(length=255), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_log', schema=None) as batch_op:
        batch_op.drop_column('answer_text')

    # ### end Alembic commands ###
