"""auto update

Revision ID: 1f9556e69308
Revises: e338511fd8c8
Create Date: 2026-05-26 02:49:01.308419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9556e69308'
down_revision: Union[str, Sequence[str], None] = 'e338511fd8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('guardian_contact', sa.String(), nullable=True),
    sa.Column('avatar_color', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.alter_column('curriculum_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('curriculum_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_curriculum_files_id'), 'curriculum_files', ['id'], unique=False)
    op.alter_column('curriculum_lessons', 'name_ar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('curriculum_lessons', 'lesson_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grades', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('grades', 'display_order')
    op.alter_column('subjects', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subjects', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subjects', 'grade_from',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subjects', 'grade_to',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'grade_to',
               existing_type=sa.INTEGER(),
               server_default=sa.text('12'),
               existing_nullable=True)
    op.alter_column('subjects', 'grade_from',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('subjects', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'published'::character varying"),
               existing_nullable=True)
    op.alter_column('subjects', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.add_column('grades', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('grades', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('grades', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('curriculum_lessons', 'lesson_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('curriculum_lessons', 'name_ar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_curriculum_files_id'), table_name='curriculum_files')
    op.alter_column('curriculum_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('curriculum_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###