"""auto update

Revision ID: 5da5767bfd81
Revises: 90993d3a38cc
Create Date: 2026-05-20 11:03:10.875476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da5767bfd81'
down_revision: Union[str, Sequence[str], None] = '90993d3a38cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_review_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_review_logs_id'), 'content_review_logs', ['id'], unique=False)
    op.create_table('curriculum_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_domains_id'), 'curriculum_domains', ['id'], unique=False)
    op.create_table('curriculum_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('option_a', sa.String(), nullable=True),
    sa.Column('option_b', sa.String(), nullable=True),
    sa.Column('option_c', sa.String(), nullable=True),
    sa.Column('option_d', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('misconception_tag', sa.String(), nullable=True),
    sa.Column('retention_tag', sa.String(), nullable=True),
    sa.Column('visual_asset_url', sa.String(), nullable=True),
    sa.Column('has_visual', sa.Boolean(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_questions_id'), 'curriculum_questions', ['id'], unique=False)
    op.create_table('curriculum_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('mastery_threshold', sa.Integer(), nullable=True),
    sa.Column('min_questions_required', sa.Integer(), nullable=True),
    sa.Column('min_visual_questions', sa.Integer(), nullable=True),
    sa.Column('remediation_required', sa.Boolean(), nullable=True),
    sa.Column('retention_review_days', sa.Integer(), nullable=True),
    sa.Column('misconception_types', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_skills_id'), 'curriculum_skills', ['id'], unique=False)
    op.create_table('skill_remediation_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.Integer(), nullable=False),
    sa.Column('remediation_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_remediation_paths_id'), 'skill_remediation_paths', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_remediation_paths_id'), table_name='skill_remediation_paths')
    op.drop_table('skill_remediation_paths')
    op.drop_index(op.f('ix_curriculum_skills_id'), table_name='curriculum_skills')
    op.drop_table('curriculum_skills')
    op.drop_index(op.f('ix_curriculum_questions_id'), table_name='curriculum_questions')
    op.drop_table('curriculum_questions')
    op.drop_index(op.f('ix_curriculum_domains_id'), table_name='curriculum_domains')
    op.drop_table('curriculum_domains')
    op.drop_index(op.f('ix_content_review_logs_id'), table_name='content_review_logs')
    op.drop_table('content_review_logs')
    # ### end Alembic commands ###