"""auto update

Revision ID: d99faf34ee33
Revises: d733cea13218
Create Date: 2026-05-23 02:11:00.562617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99faf34ee33'
down_revision: Union[str, Sequence[str], None] = 'd733cea13218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_lessons', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('admin_lessons', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.add_column('admin_questions', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('admin_questions', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.add_column('admin_skills', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('admin_skills', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.add_column('admin_subjects', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('admin_subjects', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.add_column('grades', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('grades', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.alter_column('grades', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('interactions', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('interactions', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.add_column('semesters', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('semesters', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.alter_column('semesters', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('semesters', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('units', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'curriculum_id')
    op.drop_column('units', 'country_id')
    op.alter_column('semesters', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('semesters', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('semesters', 'curriculum_id')
    op.drop_column('semesters', 'country_id')
    op.drop_column('interactions', 'curriculum_id')
    op.drop_column('interactions', 'country_id')
    op.alter_column('grades', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grades', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('grades', 'curriculum_id')
    op.drop_column('grades', 'country_id')
    op.drop_column('admin_subjects', 'curriculum_id')
    op.drop_column('admin_subjects', 'country_id')
    op.drop_column('admin_skills', 'curriculum_id')
    op.drop_column('admin_skills', 'country_id')
    op.drop_column('admin_questions', 'curriculum_id')
    op.drop_column('admin_questions', 'country_id')
    op.drop_column('admin_lessons', 'curriculum_id')
    op.drop_column('admin_lessons', 'country_id')
    # ### end Alembic commands ###