"""auto update

Revision ID: e338511fd8c8
Revises: 0648c24f1399
Create Date: 2026-05-23 02:14:32.673612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e338511fd8c8'
down_revision: Union[str, Sequence[str], None] = '0648c24f1399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_subjects', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('admin_subjects', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('admin_subjects', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('admin_subjects', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('admin_subjects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_subjects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('admin_subjects', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admin_subjects', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('admin_subjects', 'description')
    op.drop_column('admin_subjects', 'slug')
    # ### end Alembic commands ###